Allow app specific permissions
opendatakit/scan pull request #22
Opened 2017-12-11 22:45 UTC by clarlars

This depends on https://github.com/opendatakit/androidcommon/pull/37

2017-12-11 23:06 UTC, wbrunette commented
runtests

2017-12-11 23:21 UTC, jbeorse approved these changes

2017-12-11 23:24 UTC, wbrunette requested changes
Need to add to gradle

    implementation 'com.android.support:support-annotations:27.0.2'
implementation 'com.android.support:support-v13:27.0.2'

2017-12-12 00:37 UTC, wbrunette approved these changes

2017-12-12 00:39 UTC, merged